version: "2"

volumes:
  esdata:
    external: true
  mongodata:
    external: true
  fakes3data:
    external: true

services:
  elasticsearch:
    image: elasticsearch:5.0.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mongodb:
    image: mongo:3.2.10
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:3.2.4
    container_name: redis
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

  fakes3:
    image: elementar/fakes3:0.2.4.1
    container_name: fakes3
    ports:
      - "4567:4567"
    volumes:
      - fakes3data:/fakes3/data

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
